### ISSUE TITLE
why separate project

### ISSUE THREAD

**Issue by seniorivn** [cretz/doogie#47]
there are a lot of ways to do it not as a separate browser, first of all there is [qutebrowser](https://github.com/qutebrowser/qutebrowser), also [otter browser](https://otter-browser.org/) and etc

**Comment by cretz** [comment]
No particular reason, just wanted some of my UI decisions in a friendly license. Surely the same answer for me would be the answer for those projects: direction. We all have different ideas, no harm in several.

(closing because it's more of a discussion point than an issue, but feel free to keep commenting, I'll keep responding)

**Comment by seniorivn** [comment]
@cretz that's sad, it looks like you don't have technical issues with those projects, but going to solve the same technical issues in parallel, just because of the license(both open source).
anyway, it's your choice, i have no more questions.
